[package]
name = "tree-sitter-collection"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.16.1"
tree-sitter-highlight = "0.2.0"

[build-dependencies]
cc = "1.0.54"
